### PR TITLE
Update tox.ini

### PR DESCRIPTION
**Pull request by fchapoton**
refresh tox.ini

- no longer with py2
- python 3.5 to 3.9

### CODE REVIEW

**Comment by fchapoton** [comment]
may we also have a new release, please ?

**Comment by slel** [comment]
How about testing with Python 3.10 too?

**Comment by fchapoton** [comment]
ping ? :fox_face:

**Comment by vbraun** [comment]
I think this is pretty legacy at this point, but if you want to make a new release: I just added you to this project, go ahead!

**Pull request merged**
