### PR TITLE
do not use six

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by fchapoton** [comment]
Volker ? This is one of the things that force sage to keep the package "six".

**Comment by kcrisman** [comment]
> Volker ? This is one of the things that force sage to keep the package
> "six".
>
>
Hmm.  I guess that this is more of a sage-devel question, because (as I
believe) this allows people who still have sagenb worksheets to turn them
into Jupyter ones even if they are using a Python 3 Sage build.  Perhaps
that should continue at last a year beyond the complete removal of sagenb,
which I guess was in 9.1 or 9.2?

>

**Comment by fchapoton** [comment]
my changes do not break the python2 compatibility

**Comment by kcrisman** [comment]
> my changes do not break the python2 compatibility
>
>
In fact, as long as it works in Py3 that is fine - I was just pointing this
out in case it made exportsagenb not work at all.  If it does, then no
worries.

>

**Pull request merged**
